apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jsagent-app-google-client-secret
  namespace: storefront-devpython
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: teams-dev/storefront-devpython/GOOGLE_CLIENT_SECRET
